[package]
name = "any_cmp"
version = "0.2.0"
authors = ["Nossie531"]
edition = "2021"
description = "Support dynamic type comparisons."
repository = "https://github.com/nossie531/any_cmp"
license = "MIT OR Apache-2.0"
keywords = ["any", "cmp", "hash"]
